version: '3.8'

services:
  fastlane-online-solver:
    container_name: fastlane-online-solver-${ENV:-dev}
    image: ghcr.io/fastlane-labs/fastlane-online-solver:${TAG:-latest}
    environment:
      MODE: ${MODE}
      SOLVER_PK: ${SOLVER_PK}
    command:
      - --profit_margin_x10000=500
      - --frontrun_gas_margin_gwei=1
      - --fastlane_online_address=0x0E3009d01e85ac49D164E453Ec81283EAAf46fB5
      - --solver_contract_address=0x1c8930Fde5500B881ABe94f6aD9CfA10375066f6
      - --pools_config_file=pools_config_polygon.yaml
      - --pools_bin_file=pools_polygon.bin
      - --swap_paths_bin_file=swap_paths_polygon.bin
      - --mempool_connection_eth_method=alchemy_pendingTransactions
      - --max_concurrent_rpc_calls=5
      - --log_level=debug

networks:
  default:
    external: true
    name: main
