version: '3.8'

services:
  fastlane-online-solver:
    container_name: fastlane-online-solver-${ENV:-dev}
    image: ghcr.io/fastlane-labs/fastlane-online-solver:${TAG:-latest}
    environment:
      MODE: ${MODE}
      SOLVER_PK: ${SOLVER_PK}
    command:
      - --profit_margin_x10000=500
      - --frontrun_gas_margin_gwei=1
      - --fastlane_online_address=0x3BF81d7D921E7a6A1999ce3dfa3B348c50fE8DFd
      - --solver_contract_address=0x6F6D7157602bB7b2F2a1dA67dCb99d9C40605eaC
      - --pools_config_file=pools_config_polygon.yaml
      - --pools_bin_file=pools_polygon.bin
      - --swap_paths_bin_file=swap_paths_polygon.bin
      - --mempool_connection_eth_method=alchemy_pendingTransactions
      - --max_concurrent_rpc_calls=5
      - --log_level=debug

networks:
  default:
    external: true
    name: main
