version: '3.8'

services:
  fastlane-online-solver:
    container_name: fastlane-online-solver-${ENV:-dev}
    image: ghcr.io/fastlane-labs/fastlane-online-solver:latest-main
    environment:
      MODE: ${MODE}
      SOLVER_PK: ${SOLVER_PK}
    command:
      - --profit_margin_x10000=500
      - --frontrun_gas_margin_gwei=1
      - --fastlane_online_address=0x87f9B954C403Fec2A9964CFFB8AcA9CD7ED55FDf
      - --solver_contract_address=0x092C0Bf03bF0358fBb546de166B9A7901f2f3e23
      - --pools_config_file=pools_config_polygon.yaml
      - --pools_bin_file=/data/pools_polygon.bin
      - --swap_paths_bin_file=/data/swap_paths_polygon.bin
      - --mempool_connection_eth_method=alchemy_pendingTransactions
      - --max_concurrent_rpc_calls=5
      - --log_level=debug
    volumes:
      - ./data:/data

networks:
  default:
    external: true
    name: main
