pools:
  - dex_name: "quickSwap"
    dex_type: "UniswapV2"
    factory_address: "0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"
  - dex_name: "sushiswap"
    dex_type: "UniswapV2"
    factory_address: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4"
  - dex_name: "UniswapV3"
    dex_type: "UniswapV3"
    factory_address: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
  - dex_name: "UniswapV3"
    dex_type: "UniswapV3"
    factory_address: "0xBEDf73e58560024881229a0B622dB448cCfA8046"